# .github/workflows/Snake.yml
name: Generate Snake Animation

on:
  # Roda a cada 12 horas (ajuste o cron conforme sua necessidade)
  schedule:
    - cron: "0 */12 * * *"
  # Permite rodar manualmente pela aba Actions do seu repositório
  workflow_dispatch:
  # Opcional: Roda também quando você fizer push para a branch principal
  # push:
  #   branches:
  #     - main # ou master, ou o nome da sua branch principal

jobs:
  generate: # Nome do Job (pode ser qualquer nome)
    runs-on: ubuntu-latest # Define que o job vai rodar em um ambiente Linux Ubuntu mais recente

    permissions: # Permissões necessárias para o job
      contents: write # Permite que a action escreva (faça commit) no seu repositório

    steps: # Lista de passos a serem executados
      # Passo 1: Faz o checkout do código do seu repositório
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Passo 2: Gera os arquivos da animação da cobra (ESTE É O SEU TRECHO DE CÓDIGO)
      - name: Generate Snake Files
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }} # Pega o nome do dono do repositório
          # Se o repositório não for seu perfil (ex: Usuario/Usuario), coloque seu nome de usuário aqui:
          # github_user_name: SEU_NOME_DE_USUARIO_AQUI
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Passo 3: Commita os arquivos gerados de volta para o repositório
      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist # Adiciona a pasta 'dist' inteira (onde os SVGs foram salvos)
          # Verifica se há mudanças para commitar
          if ! git diff --staged --quiet; then
            git commit -m "chore: Generate contribution snake animation files"
            git push
          else
            echo "No changes to commit for snake animation."
          fi
